### ISSUE TITLE
how to run client and server

### ISSUE THREAD

**Issue by ericdai** [kxepal/python-astm#6]
c:\jinjia\python-astm\astm>python client.py
Traceback (most recent call last):
  File "client.py", line 12, in <module>
    from .asynclib import loop
ValueError: Attempted relative import in non-package

c:\jinjia\python-astm\astm>
I run client directly and get response  as above!
hot to run it  in server or client mode?

**Comment by kxepal** [comment]
Those modules are not suitable for direct run. They contains base implementations of client and server. You could inherit from those base clasess to create your own implementation. See omnilab package for example of such implementation for those analyzers.
